name: CI
on: push
jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Install modules
  #     run: yarn
  #   # - name: Run ESLint
  #   #   run: yarn install && yarn run eslint . --ext .js,.jsx,.ts,.tsx
  #   - run: "echo $ZEC"
  #     shell: bash
  #     env:
  #       ZEC: ${{secrets.ZEC}}      

  # security:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Install modules
  #       run: yarn
  #     - uses: actions/checkout@master
  #     - name: Run Snyk to check for vulnerabilities
  #       uses: snyk/actions/node@master
  #       env:
  #         SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  #     - name: check config
  #       run: cat yarn.lock |grep snyk

  scanning:
      name: GitGuardian scan
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            fetch-depth: 0 # fetch all history so multiple commits can be scanned
        - name: Install modules
          run: yarn        
        - name: GitGuardian scan
          uses: GitGuardian/ggshield-action@master
          env:
            GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
            GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
            GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
            GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
            GITGUARDIAN_API_KEY: ${{ secrets.TOMZI }}


  # repos:
  # -   repo: https://github.com/Yelp/detect-secrets
  #     rev: v1.3.0
  #     hooks:
  #     -   id: detect-secrets
  #         args: ['--baseline', '.secrets.baseline']
  #         exclude: package.lock.json